# Generated by Django 6.1.1 on 2026-09-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ABS ART', max_length=100, verbose_name='نام سایت')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='site/banner/', verbose_name='بنر اصلی')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logo/', verbose_name='لوگو')),
                ('intro_title', models.CharField(default='ABS ART', max_length=250, verbose_name='عنوان معرفی')),
                ('intro_text', models.TextField(blank=True, verbose_name='متن معرفی')),
                ('telegram', models.CharField(blank=True, max_length=250, verbose_name='تلگرام')),
                ('instagram', models.CharField(blank=True, max_length=250, verbose_name='اینستاگرام')),
                ('rubika', models.CharField(blank=True, max_length=250, verbose_name='روبیکا')),
                ('website', models.CharField(blank=True, max_length=250, verbose_name='وب\u200cسایت')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
