# Generated by Django 6.1.1 on 2026-09-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash_1', models.CharField(blank=True, max_length=255, verbose_name='رمز اصلی')),
                ('password_hash_2', models.CharField(blank=True, max_length=255, verbose_name='رمز جایگزین')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'امنیت سایت',
                'verbose_name_plural': 'امنیت سایت',
            },
        ),
    ]
