# Generated by Django 6.1.1 on 2026-09-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesecurity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesecurity',
            name='maintenance_mode',
            field=models.BooleanField(default=False, verbose_name='حالت تعمیرات'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, verbose_name='حالت تعمیرات'),
        ),
    ]
