# Generated by Django 6.1.1 on 2026-09-24 13:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام پوشه')),
                ('custom_cover', models.ImageField(blank=True, null=True, upload_to='folders/covers/', verbose_name='کاور اختصاصی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'پوشه',
                'verbose_name_plural': 'پوشه\u200cها',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('for_whom', models.CharField(blank=True, max_length=250, verbose_name='برای چه کسی')),
                ('image', models.ImageField(upload_to='works/%Y/%m/', verbose_name='تصویر')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('draft', 'پیش\u200cنویس'), ('inactive', 'غیرفعال'), ('trash', 'سطل بازیابی')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و ساعت انتشار')),
                ('is_showcase', models.BooleanField(default=False, verbose_name='ویترین منتخب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انتقال به سطل')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='works.folder', verbose_name='پوشه')),
            ],
            options={
                'verbose_name': 'طرح',
                'verbose_name_plural': 'طرح\u200cها',
                'ordering': ['-published_at'],
            },
        ),
    ]
