# Generated by Django 6.1.1 on 2026-09-27 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(max_length=64, verbose_name='شناسه ناشناس IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='works.work', verbose_name='لایک\u200cها')),
            ],
            options={
                'verbose_name': 'لایک طرح',
                'verbose_name_plural': 'لایک\u200cهای طرح',
                'constraints': [models.UniqueConstraint(fields=('work', 'ip_hash'), name='unique_work_ip_like')],
            },
        ),
    ]
